### ISSUE TITLE
Add LZ as webapp in the collab

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/LocaliZoom#1]
LZ as image annotation tool with export of point coordinates compatible with MeshView

**Comment by Majpuc** [comment]
When saving the points in LZ, "save" generates a LZ files that can be opened in MeshView, but "save as" generates a zip file that is not recognized by MeshView. Can the redundant "save as" be removed ?
![image](https://user-images.githubusercontent.com/46992863/232425127-b5aaa4b6-0aa3-4cff-bd50-58b7d937073c.png)

**Comment by Tevemadar** [comment]
`Export overlays` button is removed from LocaliZoom now, that's the one which can generate `.zip` file, which is meant for Nutil, and contains no point clouds. Now it appears in WebWarp only.
