### ISSUE TITLE
Display error for a tissue section image anchored  with VisuAlign

### ISSUE THREAD

**Issue by ingrre** [Neural-Systems-at-UIO/LocaliZoom#36]
error for s33 in this image series in Localizoom: https://localizoom.apps.hbp.eu/filmstripzoom.html?atlas=WHS_SD_Rat_v4_39um&series=https://data-proxy.ebrains.eu/api/v1/public/buckets/img-ed1bc060-d046-4352-b0fa-f7164058136b/12906_PtP_PHAL_IR-WHSSDv4-nonlin-fix.json&pyramids=buckets/img-ed1bc060-d046-4352-b0fa-f7164058136b 

It has been anchored with VisuAlign, and it looks OK there.  See png and json in this folder: Z:\HBP-Voucher_Rat-corticome\SubProject2_PosterioParietalCortex\12906\PHAL\WHSSDv4

**Comment by Majpuc** [comment]
Both the original json and the non-lin fix json contain 24 markers and the markers have identical coordinates.

**Comment by ingrre** [comment]
Also found an error in this series (section # 181) https://localizoom.apps.hbp.eu/filmstripzoom.html?atlas=WHS_SD_Rat_v4_39um&series=https://data-proxy.ebrains.eu/api/v1/public/buckets/img-953254a7-c9d2-4ad2-8a18-b32c2860e08d/F20_BDA_IR-WHSSDv4-nonlin-fix.json&pyramids=buckets/img-953254a7-c9d2-4ad2-8a18-b32c2860e08d

The VisuAlign registration is here: Z:\HBP-Voucher_Rat-corticome\SubProject1_Orbitofrontal\F20\BDA\WHSSDv4

**Comment by Tevemadar** [comment]
Yes, it's a known issue for a month or so, just I haven't got to it yet.

**Comment by Tevemadar** [comment]
Done. [33](https://localizoom.apps.hbp.eu/filmstripzoom.html?atlas=WHS_SD_Rat_v4_39um&series=https://data-proxy.ebrains.eu/api/v1/public/buckets/img-ed1bc060-d046-4352-b0fa-f7164058136b/12906_PtP_PHAL_IR-WHSSDv4-nonlin-fix.json&pyramids=buckets/img-ed1bc060-d046-4352-b0fa-f7164058136b&section=33), [181](https://localizoom.apps.hbp.eu/filmstripzoom.html?atlas=WHS_SD_Rat_v4_39um&series=https://data-proxy.ebrains.eu/api/v1/public/buckets/img-953254a7-c9d2-4ad2-8a18-b32c2860e08d/F20_BDA_IR-WHSSDv4-nonlin-fix.json&pyramids=buckets/img-953254a7-c9d2-4ad2-8a18-b32c2860e08d&section=181)
